spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/animestyle
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  application:
    name: anime-style-staff
  mail:
    host: smtp.gmail.com
    port: 587
    username: 21522348@gm.uit.edu.vn
    password: ncchoiprghnaxxnt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: Iv1.6fb2d7b8ba5826ab
            client-secret: 6434895e61d6694fa8c092bb3650a2eab7ee6b0b
            scope:
              - email
              - profile
  data:
    redis:
      host: localhost
      port: 6379
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8080
app:
  password:
    default: 12345678
management:
  health:
    mail:
      enabled: off
